### PR TITLE
Refactor create_movie to combine intermediates without reencode

### PR DESCRIPTION
**Pull request by sf302**
Reduces end-to-end encoding time by about 50%.

By outputting intermediate files as TS (transport stream), something intended to be safely concatenated at a byte level, combining the resultant video is reduced to essentially two file copy operations. One to concatenate each intermediate file into a contiguous stream, the other two remux the transport stream into the final MP4 container.

Increases amount of intermediate data at its peak from roughly 2x (originals + intermediates) to roughly 3x (originals + intermediates + transport stream), but with the speed gain on top of regaining some video quality (only lossy encoded once instead of twice), the extra disk space is _probably_ worth it.

Tested on Windows with a few saved Sentry Mode events.

### CODE REVIEW

**Comment by ehendrix23** [comment]
I like it, only thing (and correct me if I'm wrong) with this however is that if intermediate files are to be kept then in reality there won't be any actual mp4 files. Thus might wanna only do this if there is no request to keep the intermediate files then.

Can you actually do the pull request against the dev branch? That way the master really only is the released.

Appreciate your assistance in this!!

**Comment by sf302** [comment]
The intermediate TS files can be remuxed each individually into MP4 format as well without reencode. It'd simply have to be done at a later step after the combined file has been created and then just delete the TS files as soon as each intermediate MP4 is created to clean up behind itself to avoid increasing the disk footprint from 3x to 4x.

The entire 1-clip case in create_movie can be removed as well since its container still needs to be remuxed into MP4 container.

Might want to add -movflags +faststart as well just so the MP4s play nicer with web browsers.

I'll probably get around to fixing conflicts (and/or just redoing it off of dev) from changing the branch later today or maybe tomorrow.

**Comment by ehendrix23** [comment]
Just checked and seems remux works very quick, so that would work.
Only other part then would be for when all clips from different folders are merged into 1 big video file.
create_movie does this as well, but instead maybe we can then create a stream file for it and keep on adding as we do for each intermediate one.

**Comment by sf302** [comment]
The changes in https://github.com/ehendrix23/tesla_dashcam/commit/df4d45718da873248ea4d739de16a9fcb3c76376 look good to me and should accomplish basically the same thing as what I have here with the added benefit of keeping intermediates in MP4 container. I'll double check later for platform-agnosticity at least on Windows since in my tinkering yesterday some of the variants of the same operation (likely through fault solely of my own) didn't behave as expected.

Might want to keep the 'please be patient' bit, though. If someone's processing particularly large video files on a mechanical hard drive (potentially fragmented as well), it might still take awhile to remux.

**Comment by ehendrix23** [comment]
Yeah, if you could do some testing with it as well. I'll be doing the same here with different video files etc.. :-)

Feel free to grab latest from DEV as I also added -movflags +faststart and creation of chapters.

**Comment by sf302** [comment]
Tested on a different saved clips and everything works as expected on W10 for both Powershell and the standard command prompt. Closing the PR since it's superseded by your changes.

**Pull request closed without merging**
