### PR TITLE
Add support for formatted text overlay

### PR DESCRIPTION
**Pull request by JakeShirley**
NOTE: I am a C++ dev. with _very_ minor Python experience, so if my script kiddie-ness shows let me know and I can fix it! 

I tried to follow the general naming convention and what not.

This PR brings in two changes:
- Support to parse newer dashcam footage `event.json` files + the ability to create your own format for the text over (previously it was just a timestamp).  This also exposes the text values for users to make custom ffmpeg expressions.
- A small fix for ffmpeg file access when combining video files on Windows.

### Command
```
tesla_dashcam.py --halign LEFT --valign TOP --text_overlay_fmt "{event_city} ({event_latitude:.5f}, {event_longitude:.5f})\n{local_timestamp_rolling}\nRecording Reason: {event_reason}" "C:/Users/jake/Desktop/2020-05-16_13-11-53"
```
### Screen shots
With `event.json` present:
vlcsnap-2020-05-20-08h53m02s717

Without `event.json` present:
vlcsnap-2020-05-20-08h53m08s003

With bad/invalid format specifier:
vlcsnap-2020-05-20-08h55m33s192

Example with most of the variables available:
### Command
```
--halign LEFT --valign TOP --text_overlay_fmt "Default variables:\nlocal_timestamp: {local_timestamp}\nlocal_timestamp_rolling: {local_timestamp_rolling}\nevent_city: {event_city}\nevent_latitude: {event_latitude:.5f}\nevent_longitude: {event_longitude:.5f}\nevent_reason: {event_reason}\nevent_timestamp: {event_timestamp}\nevent_timestamp_countdown: {event_timestamp_countdown}\nevent_timestamp_countdown_rolling: {event_timestamp_countdown_rolling}\n\nffmpeg expression examples:\nframe_num: %{{frame_num}}\ntime code expression: %{{expr_int_format: floor((n/30)/60) : d : 2}}:%{{eif: mod(floor(n/30), 60) :d:2}}.%{{eif: mod(n, 30)+1 :d:2}}\npict_type: %{{pict_type}}" "C:/Users/jake/Desktop/2020-05-16_13-11-53"
```
### Screen shots
vlcsnap-2020-05-21-14h59m31s806

### CODE REVIEW

**Comment by JakeShirley** [comment]
cc @ehendrix23 and @magicalyak (since you seem to have interest in this repo)

**Comment by hitnrun30** [comment]
Love this, how would I go about adding this to the preferences, would i just add 3 lines
--halign LEFT 
--valign TOP 
--text-overlay-fmt "{event_city} ({event_latitude:.5f}, {event_longitude:.5f})\n{local_timestamp_rolling}\nRecording Reason: {event_reason}"

**Comment by JakeShirley** [comment]
@hitnrun30 that's correct!

**Comment by hitnrun30** [comment]
sorry it should be 
--text_overlay_fmt

thank you so much for doing the effort, is there a way to have your information in the upper left and the timestamp on the bottom middle like default

**Comment by JakeShirley** [comment]
Oh yeah you're right.  Sorry, I'll update the examples.  I tweaked that to match the other args.

Right now there is no way to do that, but I can try to look into it.  Not sure if FFMPEG supports that.

**Comment by hitnrun30** [comment]
No worries, was just wondering,

**Comment by hitnrun30** [comment]
> Have a little issue, the \n does not work on windows, i did it with both forward and backslash, any ideas?

@JakeShirley Any ideas why this is?

**Comment by JakeShirley** [comment]
Hmm really? I was able to use it on Windows via VS Code.  Mind pasting what your command line is @hitnrun30 ?

**Comment by 599316527** [comment]
> > Have a little issue, the \n does not work on windows, i did it with both forward and backslash, any ideas?
> 
> @JakeShirley Any ideas why this is?

It does not work on macOS as well. (macOS 10.15.5 & ffmpeg 4.2.1)

I tried to put a real line-break in the string and it works.

```
--text_overlay_fmt "{event_city} 
{local_timestamp_rolling}"
```

**Comment by JakeShirley** [comment]
@599316527 Not sure.  I had to do this to get it to work on my unRAID server:
```
--text_overlay_fmt $'{event_city} ({event_latitude:.5f}, {event_longitude:.5f})\n{local_timestamp_rolling}\nRecording Reason: {event_reason}\nTime Until Event: {event_timestamp_countdown_rolling}'
```

From this example: https://catonmat.net/bash-one-liners-explained-part-two#:~:text=%24%27%5Cn%27%20is%20bash%20idiomatic,z%2C%20and%20the%20newline%20character.&text=This%20one%2Dliner%20uses%20command,the%20command%20with%20its%20output.

**Pull request merged**
