### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jeanfabrice**

### CODE REVIEW

**Comment by ehendrix23** [comment]
Good catch!

**Comment by LBegnaud** [comment]
just want to give a shoutout to say thanks for this project. So simple and so powerful.

worked no problem in windows 10 with a bit of powershell i can now run this against my archive directory to merge the new events:

```
$folders = dir <archive directory>
foreach($folder in $folders){
if((dir $folder.fullname | ? name -eq "$($folder.name).mp4").count -eq 0){.\tesla_dashcam.exe $folder.fullname}
}
```

**Comment by ehendrix23** [comment]
> just want to give a shoutout to say thanks for this project. So simple and so powerful.
> 
> worked no problem in windows 10 with a bit of powershell i can now run this against my archive directory to merge the new events:
> 
> ```
> $folders = dir <archive directory>
> foreach($folder in $folders){
> if((dir $folder.fullname | ? name -eq "$($folder.name).mp4").count -eq 0){.\tesla_dashcam.exe $folder.fullname}
> }
> ```

Check out latest release (0.1.9); it can do sub folders hence your powershell might not even be required anymore. :-)

**Comment by LBegnaud** [comment]
but i don't want to merge them all into one file... unless it groups them by folder, in which case that's awesome

**Pull request merged**
