### PR TITLE
Dockerfile as part of the repository

### PR DESCRIPTION
**Pull request by jrottenberg**
It seems to come in the release only.

Took the chance to move it to alpine, alpine based images are smaller

```
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
tesla-alpine                              latest              8a8ca3143213        18 minutes ago      145MB
tesla                                     latest              52e4b60404ee        28 minutes ago      1.17GB
```

We also get a fresher ffmpeg version:

Ubuntu, using the Dockerfile from the release archive:
```
$ docker run -it --rm --entrypoint=ffmpeg tesla -version                                                                                                 
ffmpeg version 3.2.12-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100
```
versus 
```
$ docker run -it --rm --entrypoint=ffmpeg tesla-alpine -version                                                                                            
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.0 (Alpine 8.2.0)
configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-debug
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100
```

### CODE REVIEW

**Comment by jeanfabrice** [comment]
tesla_dashcam 0.1.9b and after requires psutil from pypi. I have to install gcc, musl-dev and linux-headers apk packages to correctly build psutil support.

Anyway, resulting image is still <300MB, excellent!

**Comment by jrottenberg** [comment]
oh ! let me adjust.

**Comment by jrottenberg** [comment]
Not mergeable yet, alpine's ffmpeg version is missing drawtext filter, let me see what I can do...

**Comment by jrottenberg** [comment]
Ok I did test properly this time ;-p

It has been a bit hard unfortunately :

- ffmpeg package on alpine doesn't support drawtext, so moved to my image. I can understand if you don't want to use it
- the symlink on the ttf is a bit gross, it would be nice to have support for hardcoded default, environment variables, parameters in that order. That was we can set the the fontpath in the in image
- python min version has to be 3.7 to support `capture_output` from `run`, see https://stackoverflow.com/a/53209196 hence the switch to edge

```
tesla-alpine                               latest              dd41d9cf666f        About an hour ago   412MB
```


Usage : 

```
$ docker run  -it -v ~/Desktop/tmp/TeslaCam:/mnt -w /mnt tesla-alpine  --no-notification RecentClips/test/       
Discovered 1 folders with 1 clips to process.
	Processing 1 clips in folder RecentClips/test (1/1)
		Processing clip 1/1 from 04/28/19 05:21:32 and 59 seconds long.
		Creating movie RecentClips/test/test.mp4, please be patient.
	Movie RecentClips/test/test.mp4 for folder RecentClips/test is ready.
	Creating movie RecentClips/test/test.mp4, please be patient.
Movie RecentClips/test/test.mp4 has been created, enjoy.
Total processing time: 0:00:35
```

**Comment by ehendrix23** [comment]
> oh ! let me adjust.
> 
> Ah I see, I can build from the dev branch if you prefer.
Yes, please use DEV branch as that then ensures you take in any other changes done for next release. :-)

**Comment by ehendrix23** [comment]
Just want to check and confirm I can merge this. :-) @jeanfabrice, have you tested this as well? 
I don't use Docker so relying here on both of you <g>.

**Comment by jrottenberg** [comment]
For this PR , there's more than docker, I had to change the python min version for `capture_output`

**Comment by jeanfabrice** [comment]
@jrottenberg did a perfect job reducing by a factor of 2 the overall size of the Docker image. Unfortunately, the drawback is that the image relies on a third party Docker image. As far as I'm concerned, my vote would go to a tesla_dashcam Dockerfile based on the official Python image.

**Comment by jrottenberg** [comment]
Yeah I understand your concern @jeanfabrice ,  sticking to python:3 is fine as the python version is recent enough (3.7) and the debian ffmpeg version has the drawtext plugin, it's a bigger image but stil manageable.

**Pull request closed without merging**
