### PR TITLE
Create title screen with map

### PR DESCRIPTION
**Pull request by SimonKagstrom**
Adds a new argument --title-screen-map, which generates a map of the event location and displays it for the first 3 seconds of the movie.

Looks like this:

Screenshot 2021-04-24 at 11 20 27

Edit: Rebased on the dev-branch instead, fixed various crude corners

### CODE REVIEW

**Comment by rmyadsk** [comment]
@SimonKagstrom very cool. I'd be interested in beta-testing this. In fact, I'm looking for an updated MacOS binary to include this and other fixes (see #149 and #150). Could you please help out? @ehendrix23 seems unavailable.

**Comment by SimonKagstrom** [comment]
I just installed ffmpeg via homebrew, if I remember correct that was enough to get tesla_dashcam to work on OSX. I don't know how the binary is built, so I'd rather not go there!

If you want to test it, you should clone my git repo and the create-title-screen-with-map branch. It's certainly a bit crude though, I must admit! Serves my purposes though :-)

**Comment by rmyadsk** [comment]
@SimonKagstrom thanks for these recent pushes. What's next for this feature in general availability: would @ehendrix23 need to roll them into their code, then rebuild binaries? NB: I've been hoping for an updated MacOS binary since February #149  and so am not optimistic one will be forthcoming.

If you have instructions how I might clone your repo and make a workable build from it, could you please post any notes you might have here, and I'll do my best. As information, I am running macOS Big Sur 11.3.1.

**Comment by SimonKagstrom** [comment]
I've merged all my changes into the `simon-all` branch, here https://github.com/SimonKagstrom/tesla_dashcam/tree/simon-all

So to get "everything", you can clone that repo and do `git checkout simon-all`.


I've never used the binary repo, and not quite sure how it's built. I'm also using OSX (apart from Raspberry Pi), and I think the easiest way is to just install OSX homebrew and then something like

```
brew install ffmpeg 
brew install python3    # Maybe not needed
pip3 install staticmac  # Might have been pip install
```

and you should have everything needed for running with the `--title_screen_map` option.


As a side-note, my real goal is this project: https://github.com/SimonKagstrom/tesla_dashcam_manager, which aims to automate teslausb + tesla_dashcam  + pigallery2 (for viewing) through the use of a dockerized Raspberry Pi  "server".

**Comment by rmyadsk** [comment]
> I've never used the binary repo

C'mon, really?

Binary != repo. Binary == a thing that is distributable to users as a monolithic package, one that can be easily installed by a user without, say, compilation. This seems something @ehendrix23 seems no longer to be interested in.

I will endeavor to roll my own with your instructions, and report back results.

I do love the tesla_dashcam_manager idea! I am also a fan of (marcone)Teslausb.

**Comment by SimonKagstrom** [comment]
I guess I should have said binary package. I knew from the start that I had to make some modifications, so I never bothered looking into how it's built and run.

**Comment by rmyadsk** [comment]
Aye, there's the rub.

No sweat. I don't mind trying to hack up my own runtime this time, though most users - those you'd encounter in the wild, say, marcone/teslausb users - might. This would then be a barrier to entry for many of them.

A larger concern would be @ehendrix23 - as the guy upstream, he seems to be either unaware of your commits or altogether absent to the project, both of which are bad for connecting non-expert-level users with the latest and best version of software. See #149 #150 et al. - I mean, it doesn't even match documentation.

**Comment by SimonKagstrom** [comment]
Well, I'd give @ehendrix23 some slack, after all it's fairly time consuming to maintain a project and probably there's other things going on which are more important right now :-). Also huge kudos to @ehendrix23  for actually implementing this, I know I wouldn't be able to create something similar having spent loads of time just to understand how to insert an image at the start of a video stream!

Anyway, that's also sort of the aim with tesla_dashcam_manager, it builds as a docker image which is uploaded to dockerhub, so really all that's needed is to add it to a docker-compose.yml on your Raspberry, pull and restart the stack and it should be up and running. However, that's a separate project, so enough about that ;-)

**Comment by rmyadsk** [comment]
Per #149 

> Still "supported" but at very low priority. I will see to release new version this or next week which then includes executables.

Timestamp: March 8. T+63 days: none of those things have since happened. This feels increasingly like a graveyard project.

**Pull request merged**
